# Generated by Django 3.1.4 on 2020-12-27 09:33

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('football', '0002_season'),
    ]

    operations = [
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('app_id', models.IntegerField()),
                ('name', models.CharField(max_length=100)),
                ('shortName', models.CharField(max_length=100)),
                ('tla', models.CharField(max_length=100)),
                ('crestUrl', models.CharField(max_length=100)),
                ('address', models.CharField(max_length=100)),
                ('phone', models.CharField(max_length=100)),
                ('website', models.CharField(max_length=100)),
                ('email', models.CharField(max_length=100)),
                ('founded', models.IntegerField()),
                ('clubColors', models.CharField(max_length=100)),
                ('venue', models.CharField(max_length=100)),
                ('lastUpdated', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
    ]
