# Generated by Django 3.1.4 on 2020-12-27 10:28

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('football', '0004_auto_20201227_0959'),
    ]

    operations = [
        migrations.CreateModel(
            name='Match',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('app_id', models.IntegerField()),
                ('utcDate', models.DateTimeField(default=django.utils.timezone.now)),
                ('status', models.CharField(max_length=100, null=True)),
                ('matchday', models.IntegerField()),
                ('stage', models.CharField(max_length=100, null=True)),
                ('group', models.CharField(max_length=100, null=True)),
                ('lastUpdated', models.DateTimeField(default=django.utils.timezone.now)),
                ('score_winner', models.CharField(max_length=100, null=True)),
                ('score_duration', models.CharField(max_length=100, null=True)),
                ('score_fullTime_homeTeam', models.IntegerField(null=True)),
                ('score_fullTime_awayTeam', models.IntegerField(null=True)),
                ('score_halfTime_awayTeam', models.IntegerField(null=True)),
                ('score_extraTime_awayTeam', models.IntegerField(null=True)),
                ('score_penalties_homeTeam', models.IntegerField(null=True)),
                ('score_penalties_awayTeam', models.IntegerField(null=True)),
                ('awayTeam', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='awayTeam', to='football.team')),
                ('homeTeam', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='homeTeam', to='football.team')),
                ('season', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='football.season')),
            ],
        ),
    ]
