# Generated by Django 3.1.4 on 2020-12-27 10:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('football', '0005_match'),
    ]

    operations = [
        migrations.AlterField(
            model_name='competition',
            name='app_id',
            field=models.IntegerField(unique=True),
        ),
        migrations.AlterField(
            model_name='match',
            name='app_id',
            field=models.IntegerField(unique=True),
        ),
        migrations.AlterField(
            model_name='match',
            name='awayTeam',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='awayTeam', to='football.team', to_field='app_id'),
        ),
        migrations.AlterField(
            model_name='match',
            name='homeTeam',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='homeTeam', to='football.team', to_field='app_id'),
        ),
        migrations.AlterField(
            model_name='match',
            name='season',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='football.season', to_field='app_id'),
        ),
        migrations.AlterField(
            model_name='season',
            name='app_id',
            field=models.IntegerField(unique=True),
        ),
        migrations.AlterField(
            model_name='team',
            name='app_id',
            field=models.IntegerField(unique=True),
        ),
    ]
