# Generated by Django 3.1.4 on 2020-12-27 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('football', '0006_auto_20201227_1054'),
    ]

    operations = [
        migrations.AddField(
            model_name='match',
            name='score_extraTime_homeTeam',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='match',
            name='score_halfTime_homeTeam',
            field=models.IntegerField(null=True),
        ),
    ]
