# Generated by Django 3.1.4 on 2021-01-31 18:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('football', '0007_auto_20201227_1100'),
    ]

    operations = [
        migrations.CreateModel(
            name='Standing',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.IntegerField(null=True)),
                ('playedGames', models.IntegerField(null=True)),
                ('form', models.CharField(max_length=100, null=True)),
                ('won', models.IntegerField(null=True)),
                ('draw', models.IntegerField(null=True)),
                ('lost', models.IntegerField(null=True)),
                ('points', models.IntegerField(null=True)),
                ('goalsFor', models.IntegerField(null=True)),
                ('goalsAgainst', models.IntegerField(null=True)),
                ('goalDifference', models.IntegerField(null=True)),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='team', to='football.team', to_field='app_id')),
            ],
        ),
    ]
