# Generated by Django 3.2 on 2021-04-23 11:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('football', '0011_auto_20210423_1702'),
    ]

    operations = [
        migrations.AlterField(
            model_name='predictions',
            name='away',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='predictions',
            name='home',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
